### ISSUE TITLE
API returns an empty list for domain facets

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#100]
When fetching the facets definitions for each domain, only the 'general' domain works, which is this endpoint:
https://supersead.humlab.umu.se/query/api/facets/domain/general

None of the other domains work, such as:
https://supersead.humlab.umu.se/query/api/facets/domain/palaeoentomology
https://supersead.humlab.umu.se/query/api/facets/domain/archaeobotany
https://supersead.humlab.umu.se/query/api/facets/domain/dendrochronology

They all return empty lists: `[]`

**Comment by roger-mahler** [comment]
Fixed after update of staging database.
