### ISSUE TITLE
Countries and Region facets fails when used together

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#103]
When using the Countries and Region facets, without any selections, only the top one will load, see these images:

![image](https://user-images.githubusercontent.com/34707290/225580993-b0a4af26-3751-43e7-8f47-059b9524af3a.png)

![image](https://user-images.githubusercontent.com/34707290/225581084-67c0e77c-ed24-4436-9902-b23e806c5f6e.png)

This is what the end of the request for the bottom facet looks like:

![image](https://user-images.githubusercontent.com/34707290/225581462-5798c31d-4e90-417d-a515-9c0f156db4c1.png)

The items are actually being returned, but for some reason their Name and DisplayName attributes are null.

**Comment by roger-mahler** [comment]
Closing since the problem seems to be fixed in latest release.
