### ISSUE TITLE
Filtret "Region" beter sig på ett oväntat sätt

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_query_api#111]
Ta fram filtret "Region"
![image](https://github.com/humlab-sead/sead_browser_client/assets/100921064/6d218509-c744-443a-ac39-64081c2d1fbe)

1. Klicka på "Åland Kastelholm". Checkboxen markeras och kartan zoomar in på Åland. Alla fyra siterna visas på kartan (förväntat är att bara "Kastelholm visas).

```sql
SELECT DISTINCT tbl_sites.site_id AS id_column, tbl_sites.site_name AS name,
    coalesce(latitude_dd, 0.0) AS latitude_dd, coalesce(longitude_dd, 0) AS longitude_dd
FROM tbl_sites
INNER JOIN tbl_site_locations ON tbl_site_locations."site_id" = tbl_sites."site_id"
INNER JOIN tbl_locations AS region ON region."location_id" = tbl_site_locations."location_id"
WHERE 1 = 1
  AND  (region.location_id ::text in ('3968', '3968', '3968', '3968'))
  AND region.location_type_id in (2, 7, 14, 16, 18)
```

2. Klicka på "Åland Otterböte". Checkboxen markeras inte. Kartan zoomar ut till default-lägen (hela världen med alla sajter). (Förväntat resultat är att checkboxen markeras och att kartan fortsätter visa Åland.)

```sql
SELECT DISTINCT tbl_sites.site_id AS id_column, tbl_sites.site_name AS name,
       coalesce(latitude_dd, 0.0) AS latitude_dd, coalesce(longitude_dd, 0) AS longitude_dd
FROM tbl_sites
WHERE 1 = 1
```

3. Vid klick igen på "Åland Otterböte" så markeras checkboxen och kartan zoomar in igen på Åland och visar de fyra punkterna. (Förväntat är att Kastelholm och Otterböte visas på kartan.)

```sql
SELECT DISTINCT tbl_sites.site_id AS id_column, tbl_sites.site_name AS name, coalesce(latitude_dd, 0.0) AS latitude_dd, coalesce(longitude_dd, 0) AS longitude_dd
FROM tbl_sites
INNER JOIN tbl_site_locations ON tbl_site_locations."site_id" = tbl_sites."site_id"
INNER JOIN tbl_locations AS region ON region."location_id" = tbl_site_locations."location_id"
WHERE 1 = 1
  AND (region.location_id ::text in ('3968', '3968', '3968', '3968'))
  AND region.location_type_id in (2, 7, 14, 16, 18)
```

Varför visas alla fyra punkterna för Åland på kartan när man markerar en i filtret? Borde väl bara vara den site man valt? När man scrollar neråt i filtret och sen tillbaka så är alla fyra markerade. Om det är så att de hänger ihop borde alla markeras vid första klicket på en av posterna.
Varför zoomar kartan ut när man försöker bocka för nästa site på Åland efter att ha markerat den första?
Det här gäller för en mängd olika sajter, det finns tydligen nån koppling som inte är uppenbar.

**Comment by roger-mahler** [comment]
The problem is that the facet is a location filter but site names are displayed in the checkbox which doesn't make sence. Removing  site name from checkbox.
