### ISSUE TITLE
Filter for tbl_analysis_entity_ages

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#115]
Maybe something like:

{
        "FacetId": X,
        "FacetCode": "ae_ages",
        "DisplayTitle": "Time",
        "Description": "",
        "FacetGroupKey": "space_time",
        "FacetTypeKey": "range",
        "IsApplicable": true,
        "IsDefault": false,
        "AggregateType": "",
        "AggregateTitle": "Number of samples",
        "FacetGroup": {
            "FacetGroupKey": "space_time",
            "DisplayTitle": "Space/Time",
            "Description": "Space/Time"
        }
}

**Comment by roger-mahler** [comment]
Deployed to staging.
