### ISSUE TITLE
Mer avancerat region filter?

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#117]
Dendro-folket efterfrågar någon form av mer avancerad regional sökning.

De behöver kunna söka på: län, landskap, kommun, socken, parish/församling. Särskilt landskap är ofta relevant.

Behovet skulle delvis uppfyllas av implementering av filtret för geografiska polygoner.

Frågeställningar:
Vilka filter behöver vi?
Vore det lämpligt att använda någon form av fler-stegs filter?
Hur hantera att regioner förändras över tid?
Kan vi integrera regionerna med kartan så att den valda polygonen går att visa?

**Comment by johanvonboer** [comment]
We need one filter location_type and one for location (existing Region filter)

**Comment by roger-mahler** [comment]
[20240327_DML_FACET_LOCATION_TYPE](https://github.com/humlab-sead/sead_change_control/issues/261) adds location type filter.

**Comment by roger-mahler** [comment]
The data only support support limited filtering on requested administrative divisions (län, landskap, kommun, socken, parish/församling). Adding a "location type" filter in conjunction with the existing "region" filter partially solves requested feature.
Closing this issue, please open new issue for additional feature requests,
