### ISSUE TITLE
Return full data span indicators when loading range filter

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#16]
When loading a range facet which has selections/picks, the full range of (the range without selections) needs to be hinted at to the client by including just the max & min values.

Like this:
facetObject.fullextent = [0, 2904]

Client can't render the slider properly without this information.

**Comment by roger-mahler** [comment]
The following data has been added when a range facet is loaded:

 ```
 "IntervalInfo": {
    "FullExtent": {
      "Lower": 0.0000000000,
      "Upper": 2981.0000000000,
      "Count": 120
    }
  },
```
