### ISSUE TITLE
 Missing data in biblio

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#23]
This example query returns a result where the biblio_author column is null. In sead_master_8 there is author information for this sample group.

SELECT tbl_sample_group_references.biblio_id,
    tbl_sample_group_references.sample_group_reference_id,
    tbl_sample_group_references.sample_group_id,
    tbl_biblio.authors AS biblio_author,
    tbl_biblio.bugs_reference AS biblio_bugs_reference,
    tbl_biblio.doi AS biblio_doi,
    tbl_biblio.isbn AS biblio_isbn,
    tbl_biblio.notes AS biblio_notes,
    tbl_biblio.title AS biblio_title,
    tbl_biblio.year AS biblio_year,
    tbl_biblio.full_reference AS biblio_full_reference,
    tbl_biblio.url AS biblio_url
   FROM public.tbl_sample_group_references
     LEFT JOIN public.tbl_biblio ON tbl_sample_group_references.biblio_id = tbl_biblio.biblio_id
	 WHERE public.tbl_sample_group_references.sample_group_id = 1

**Comment by roger-mahler** [comment]
See humlab-sead/sead_change_control/#3.

**Comment by roger-mahler** [comment]
Duplicate.
