### ISSUE TITLE
Country filter error

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#34]
REST-plugin config:

### Issue with Country filter

POST https://seadserv.humlab.umu.se:8089/api/result/load
Sec-Fetch-Mode: cors
mode: cors
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/json; charset=UTF-8

{"facetsConfig":{"requestId":2,"requestType":"populate","targetCode":"country","triggerCode":"country","facetConfigs":[{"facetCode":"country","position":1,"picks":[{"pickType":1,"pickValue":64,"text":64}],"textFilter":""}]},"resultConfig":{"requestId":2,"sessionId":"1","viewTypeId":"map","aggregateKeys":["site_level"]}}

**Comment by roger-mahler** [comment]
Facet has alias which is missing from SQL:
```sql
            SELECT DISTINCT tbl_sites.site_id AS id_column, tbl_sites.site_name AS name, coalesce(latitude_dd, 0.0) AS latitude_dd, coalesce(longitude_dd, 0) AS longitude_dd
            FROM tbl_sites 
                  left join tbl_site_locations  on tbl_site_locations."site_id" = tbl_sites."site_id" 
            WHERE 1 = 1
            AND ( (countries.location_id::int in (64)) )
```

**Comment by roger-mahler** [comment]
Should be fixed now.
