### ISSUE TITLE
MS filter internal server error

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#36]
MS filter with selections fails by giving an internal server error.

REST:

### Testing MS filter

POST https://seadserv.humlab.umu.se:8089/api/facets/load
Sec-Fetch-Mode: cors
mode: cors
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/json; charset=UTF-8

{
  "requestId": 1,
  "requestType": "populate",
  "targetCode": "tbl_denormalized_measured_values_33_0",
  "facetConfigs": [
    {
      "facetCode": "tbl_denormalized_measured_values_33_0",
      "position": 1,
      "picks": [100, 200],
      "textFilter": ""
    }
  ]
}

**Comment by roger-mahler** [comment]
Same as #30.

**Comment by roger-mahler** [comment]
Proper way of specifying picks:
```
{
...
        "picks":[
            { "pickType": 2, "pickValue": "50", "text": "50"},
            { "pickType": 3, "pickValue": "100", "text": "100"}
        ],
...
}
```
