### ISSUE TITLE
Result load fails

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#41]
VSCODE REST config:

### Failing fetch: Site-filter with a pick + MS-filter
POST https://seadserv.humlab.umu.se:8089/api/result/load
Sec-Fetch-Mode: cors
mode: cors
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/json; charset=UTF-8

{ 
   "facetsConfig":{ 
      "requestId":2,
      "requestType":"populate",
      "targetCode":"tbl_denormalized_measured_values_33_0",
      "triggerCode":"tbl_denormalized_measured_values_33_0",
      "facetConfigs":[ 
         { 
            "facetCode":"sites",
            "position":1,
            "picks":[ 
               { 
                  "pickType":1,
                  "pickValue":261,
                  "text":261
               }
            ],
            "textFilter":""
         },
         { 
            "facetCode":"tbl_denormalized_measured_values_33_0",
            "position":2,
            "picks":[ 

            ],
            "textFilter":""
         }
      ]
   },
   "resultConfig":{
      "requestId":2,
      "sessionId":"1",
      "viewTypeId":"map",
      "aggregateKeys":[ 
         "site_level"
      ]
   }
}

**Comment by roger-mahler** [comment]
Same as #37. Affects all multi-facet filters with at least one range filter...
