### ISSUE TITLE
Facet groups needs titles

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#53]
When using the API for fetching filters via https://seadserv.humlab.umu.se:8089/api/facets only the facet group key/id is given, we also need a pretty-printed title for the group, similar to the DisplayTitle attribute given for the filter name in the link above.

**Comment by roger-mahler** [comment]
This is added in December 2019 release. Each returned facet object will have an additional  `FacetGroup` property with `DisplayTitle` and `Description`.
The information is repeated for each facet.

```json
{
  "FacetId": 3,
  "FacetCode": "tbl_denormalized_measured_values_33_0",
  "DisplayTitle": "MS ",
  "Description": "MS ",
  "FacetGroupKey": "measured_values",
  "FacetTypeKey": "range",
  "IsApplicable": true,
  "IsDefault": false,
  "AggregateType": "",
  "AggregateTitle": "Number of samples",
  "FacetGroup": {
    "FacetGroupKey": "measured_values",
    "DisplayTitle": "Measured values",
    "Description": "Measured values"
  }
}
```
