### ISSUE TITLE
Guide: How to create new facets

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_query_api#57]
The introduction of "portals" into Super SEAD requires a number of new facets to be created. 
Currently. no user interface exists to achieve this task (a proposal exists though).

The SEAD change control system has functions that allow facets to be specified using a JSON notation.

The purpose of this issue is to:

- Describe the facet database model
- Give an overview of the facet query builder domain logic
- Describe how to specify a new facet in JSON format
- Specify how the JSON can be used in an SQL DML change and added to SEAD CC system
- How to test a new facet

**Comment by roger-mahler** [comment]
New facets can now be created using JSON as exemplified in this [scripts](https://github.com/humlab-sead/sead_change_control/blob/dc0c9f599bb6c11ca2f7c6533c3e03568dad6ad3/sead_api/deploy/20190101_DML_FACET_SCHEMA.sql#L608) that populates the facet schema.

**Comment by johanvonboer** [comment]
This is a minor thing but PB has expressed a wish to have the filters and groups sorted in a particular order, it would be good if this sort order could be a part of the filter specification in the form of a integer which will act as a weighting value.

**Comment by roger-mahler** [comment]
Closing this issue.
