### ISSUE TITLE
Incorrect data points showing when selecting Master datasets second time

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_query_api#59]
I'm not sure what's causing this, but it appears to be supersead related. I am also not entirely sure that it is a problem, but wanted to flag it for more investigation (Phil & Love?).

When filtering by Master dataset, the first filter application works as expected:
![image](https://user-images.githubusercontent.com/35995002/75152388-32fd3a80-5709-11ea-91a5-3e942f79a6ab.png)

Adding an additional master dataset to the selected items works correctly:
![image](https://user-images.githubusercontent.com/35995002/75152458-5922da80-5709-11ea-9e75-4b62441c1b23.png)

Removing the first selection from the list does not always work, and either leaves the set there or _even adds more data_. Below I added each master dataset, then removed the Wood one, but the latter remained.
![image](https://user-images.githubusercontent.com/35995002/75153512-dbac9980-570b-11ea-87b1-c11b9f0300aa.png), but the latter remained.

Problem exists in both Firefox and Edge.

**Comment by johanvonboer** [comment]
As far as I can tell this is a backend issue so I moved it to sead_query_api repository

**Comment by roger-mahler** [comment]
Sorry for late reply, but I haven't been able to reproduce this problem. I thing worth mentioning is that each request result returned to the client contains the actual SQL that was generated by the query engine. It would simplify debugging  if the client had a feature to display this query, and the configuration sent to the query engine. It is quite easy, though, to retrieve this information using the web browsers developer tools. For Chrome, the procedure would be:

### Press F12 to open the developer tools.
![Image 1](https://user-images.githubusercontent.com/17061116/79948520-4e1fc880-8474-11ea-8aac-b8cd1e480a9f.png)

**Comment by johanvonboer** [comment]
I believe this turned out to be a frontend issue that is now fixed - I forgot I had moved this issue here, sorry!
