### ISSUE TITLE
Result load of "tabular" isotope data fails

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#62]
When selecting the "Isotopes" portal, results are provided as sites on the map, but when switching to Spreadsheet result view, it is empty, because no results are returned if "viewTypeId" in the request JSON is set to "tabular", but results are returned for the same request JSON if the "viewTypeId" is set to "map".

Example viewstate:
http://supersead.humlab.umu.se/viewstate/4eHRiVIJp

(switch between Spreadsheet and Map)

**Comment by roger-mahler** [comment]
Record type for method IRMS is not specified i.e. set to a NULL value in `tbl_methods`. The facet only uses inner joins on all routes in query which filters out these records.

```sql
SELECT tbl_methods.*
FROM tbl_dataset_masters
JOIN tbl_datasets USING (master_set_id)
JOIN tbl_methods USING (method_id)
LEFT JOIN tbl_record_types USING (record_type_id)
WHERE 1 = 1
  AND master_set_id = 11;
```
Two methods have a non-specified record type:

```sql
SELECT tbl_methods.*
FROM tbl_methods
WHERE record_type_id IS NULL;

175	IRMS, "Isotope-ratio mass spectrometry"	
174 "AE", "Acid Extraction"
```
Closing this since it is a data error.
