### ISSUE TITLE
@2020-03 release: Create changelog

### ISSUE THREAD

**Issue by roger-mahler** [humlab-sead/sead_query_api#73]
See [CHANGELOG](https://github.com/humlab-sead/sead_query_api/blob/master/CHANGELOG.md).

**Comment by roger-mahler** [comment]
@johanvonboer Could you please check this change log and estimate when you can adapt the browser client to the changes? I hope it won't be to much work for you, unless there are requirements that I'm not aware of.

**Comment by johanvonboer** [comment]
Seems easy to implement, but I would like to have a live version of the new API before I start the work, to make sure I understand exactly how it works. Once it's online I can probably do the conversion in a few hours.
