### ISSUE TITLE
Expose version of API

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#77]
Would be good if it was possible to retrieve the current version of the API being used, via for example: /api/version

Which would result in something like

{
  date: "2020.04",
  version: "1.2.0"
}

This would be useful for me to store in viewstates, especially if this version number also denotes the database version, but even if that's not so then it could still be useful for debugging.

**Comment by roger-mahler** [comment]
Changed  GET method `api/values` to return current version as values "2020", "03". Old version will still return "value1", "value2".

**Comment by roger-mahler** [comment]
Will add a `api/version` in later release, but I prefer not to make changes in deployed version..
