### ISSUE TITLE
Outdated repositories in Dockerfile

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_query_api#78]
References to the follow repositories in the Dockerfile no longer work:
mcr.microsoft.com/dotnet/core/aspnet:3.1-stretch-slim
mcr.microsoft.com/dotnet/core/sdk:3.1-stretch

In the latest build I replaced them with:
mcr.microsoft.com/dotnet/core/aspnet:3.1
mcr.microsoft.com/dotnet/core/sdk:3.1

This made the Dockerfile build ok, but I don't know if it will affect anything other than making the image a little larger?

**Comment by roger-mahler** [comment]
This is OK. Dockerfile is changed to buster-slim, but any image will work, even alpine.
